version: "3.9"

services:
  crowdtraq:
    build: .
    container_name: crowdtraq2
    ports:
      - "7890:7890"
      - "8081:8081"
    env_file:
      - .env
    command: ["python", "-m", "app.main"]
